### PR TITLE
web socket enhancement

### LINKED ISSUE #18: Implement Notification System in your Chat App
The next task for you is the implementation of a notification system:
- This would notify all users whenever new messages are posted in chatrooms they are a part of. 
- This could be through real-time WebSocket notifications, polling, or any other suitable method. 
- We can also allow users to set their notification preferences, such as choosing to receive notifications for all messages, mentions, or messages in specific chatrooms.
- Ensure that the notification system integrates seamlessly with the existing chat app microservice.
- Make any necessary updates to the database layer to handle notification-related data efficiently.
- Prioritize efficiency in your implementation to minimize server load and optimize real-time notifications.
- Write unit tests to validate the functionality of the notification system
- Update the Swagger API documentation to include information about any new endpoints related to chatroom notifications (if required).

We believe that successfully implementing this notification system will not only enhance the chat app's functionality but also provide you with valuable experience and greatly enhance your coding skills. 

Important: Please refrain from seeking assistance from ChatGPT for every issue. Instead, utilize it only when you encounter exceptionally challenging problems. If you do seek help, ensure that you thoroughly understand the information you are obtaining rather than simply copying it.

If you have any questions or need further assistance during this task, please don't hesitate to reach out. Good luck, and we look forward to seeing your work!

### PR DESCRIPTION
**Pull request by Hammad887**
1. Implemented Web Socket for real time notifications.
2. Unit tests written for the web socket package
3. Made some changes in swagger.yaml and db layer (Found some issues with CRUD operations while testing)
4. Implemented Validation Checks to make sure only authenticated users can enter and send message to a particular chatroom.

### CODE REVIEW

File: cmd/chat_app_server/main.go [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package main
 
 import (
+	"github.com/Hammad887/chat-app/websocket"
```
Comment (shahzadhaider1) [inline cmd/chat_app_server/main.go]: sort imports

File: db/mysql/ops.go [hunk 2]
```diff
@@ -59,11 +59,25 @@ func (c *client) ListChatRoom(ctx context.Context) ([]*domain.ChatRoom, error) {
...
+		var userID string
+		if err := rows.Scan(&chatRoom.ID, &chatRoom.Name, &userID); err != nil {
+			log.Fatal(err)
+		}
+		chatRoom.Users = append(chatRoom.Users, userID)
+		userIDs[userID] = struct{}{}
 	}
 
 	return &chatRoom, nil
+
```
Comment (shahzadhaider1) [inline db/mysql/ops.go]: no need for this blank line

File: swagger.yaml [hunk 3]
```diff
@@ -47,6 +47,37 @@ paths:
...
+      parameters:
+        - name: 'chatroom'
+          in: 'body'
+          required: true
+          description: 'create chatroom Payload'
+          schema:
+            $ref: '#/definitions/ChatroomInfo'
+      responses:
+        200:
+          description: Successful created a chatroom
```
Comment (shahzadhaider1) [inline swagger.yaml]: Successfully created a chatroom

File: swagger.yaml [hunk 4]
```diff
@@ -47,6 +47,37 @@ paths:
             type: string
           description: Server error
 
+  /createChatRoom:
+    post:
+      description: 'Creates a new chatroom with the provide name'
+      tags:
+        - service
+      operationId: ChatRoom
```
Comment (shahzadhaider1) [inline swagger.yaml]: For operationId, you should ideally use a verb to describe the action being performed. For example, you could use CreateChatRoom here

File: swagger.yaml [hunk 5]
```diff
@@ -47,6 +47,37 @@ paths:
...
+          description: 'create chatroom Payload'
+          schema:
+            $ref: '#/definitions/ChatroomInfo'
+      responses:
+        200:
+          description: Successful created a chatroom
+          schema:
+            $ref: '#/definitions/ChatroomSuccess'
+        400:
+          description: Bad Request
```
Comment (shahzadhaider1) [inline swagger.yaml]: the `parameter` in this API is `required`, so the request won’t be allowed if the body is missing/incorrect. 
are there any other cases where this 400 response could be utilised?

File: swagger.yaml [hunk 6]
```diff
@@ -47,6 +47,37 @@ paths:
...
+        404:
+          schema:
+            type: string
+          description: User not found
```
Comment (shahzadhaider1) [inline swagger.yaml]: User not found?

File: websocket/websocket-server.go [hunk 7]
```diff
@@ -0,0 +1,295 @@
...
+import (
+	"context"
+	"encoding/json"
+	"fmt"
+	"log"
+	"net/http"
+	"strconv"
+
+	"github.com/Hammad887/chat-app/db"
+	"github.com/Hammad887/chat-app/db/mysql"
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: sort imports

File: websocket/websocket-server.go [hunk 8]
```diff
@@ -0,0 +1,295 @@
...
+var ctx context.Context
+
+var DbClient db.DataStore
+
+var ChatRoomList = make(map[string]*ChatRoom)
+
+type ChatRoom struct {
+	chatRoomId string
+	clients    []*Clients
+}
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: we have a struct with the same name in the models package. why that wasn’t used here?

File: websocket/websocket-server.go [hunk 9]
```diff
@@ -0,0 +1,295 @@
...
+	},
+}
+
+func RunWebsocketServer() {
+
+	options := db.Option{
+		TestMode: false, // Set the appropriate value for TestMode here
+	}
+
+	DbClient, _ = mysql.NewClient(options)
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: we have already created a database client in runtime file, right? 
why that wasn’t used here?
why multiple database clients in a single application?

File: websocket/websocket-server.go [hunk 10]
```diff
@@ -0,0 +1,295 @@
...
+var upgrader = websocket.Upgrader{
+	ReadBufferSize:    1024,
+	WriteBufferSize:   1024,
+	EnableCompression: true,
+	CheckOrigin: func(r *http.Request) bool {
+		return true
+	},
+}
+
+func RunWebsocketServer() {
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: add comments for exported functions

File: websocket/websocket-server.go [hunk 11]
```diff
@@ -0,0 +1,295 @@
...
+	router.Use(handlers.CORS(headers, origins))
+
+	go router.HandleFunc("/ws", ClientSocket)
+	fmt.Println("Server is running on port 8081")
+
+	// Start your server
+	http.ListenAndServe(":8085", router)
+}
+
+func ClientSocket(w http.ResponseWriter, r *http.Request) {
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: add comments for exported functions

File: websocket/websocket-server.go [hunk 12]
```diff
@@ -0,0 +1,295 @@
...
+		log.Print("upgrade:", err)
+		return
+	}
+	defer Conn.Close()
+
+	for {
+		messageType, requestByte, err := Conn.ReadMessage()
+
+		if err != nil {
+			log.Println("ERROR read", err)
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: use Error() here

File: websocket/websocket-server.go [hunk 13]
```diff
@@ -0,0 +1,295 @@
...
+					responseBytes, _ := json.Marshal(Response)
+					WriteOnSocket(responseBytes, messageType, Conn)
+					break
+				}
+			}
+
+			if _, ok := requestJson["sender_id"]; ok {
+				if !ok {
+					Response := make(map[string]interface{})
+					Response["request_type"] = "connect_to_chat_room"
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: I see "connect_to_chat_room" and other magic values used in multiple places. 
Consider using constants for these.

File: websocket/websocket-server.go [hunk 14]
```diff
@@ -0,0 +1,295 @@
...
+		default:
+			//	TODO: Handle unknown request and update client
+			log.Println("Unknown Method: ", requestJson["requestType"])
+			break
+		}
+	}
+
+}
+
+func WriteOnSocket(responseBytes []byte, messageType int, Conn *websocket.Conn) {
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: add comments for exported functions

File: websocket/websocket-server.go [hunk 15]
```diff
@@ -0,0 +1,295 @@
...
+	case float64:
+		TmpStr := strconv.FormatFloat(ThisInterface.(float64), 'f', 10, 64)
+		if TmpStr[(len(TmpStr)-10):] == "0000000000" {
+			return TmpStr[:(len(TmpStr) - 11)]
+		}
+		return TmpStr
+	default:
+		return ThisInterface.(string)
+	}
+}
```
Comment (shahzadhaider1) [inline websocket/websocket-server.go]: this function converts interface to multiple types, why only use string in the function name?

File: websocket/websocket-server_test.go [hunk 16]
```diff
@@ -0,0 +1,47 @@
+package websocket
+
+import (
+	"net/http"
+	"net/http/httptest"
+	"strings"
+	"testing"
+
+	"github.com/gorilla/websocket"
+
```
Comment (shahzadhaider1) [inline websocket/websocket-server_test.go]: no need for this space

File: websocket/websocket-server_test.go [hunk 17]
```diff
@@ -0,0 +1,47 @@
...
+	serverURL := "ws" + strings.TrimPrefix(server.URL, "http")
+
+	// Create a WebSocket connection to the server
+	conn, _, err := websocket.DefaultDialer.Dial(serverURL, nil)
+	if err != nil {
+		t.Fatalf("Failed to dial server: %v", err)
+	}
+	defer conn.Close()
+
+}
```
Comment (shahzadhaider1) [inline websocket/websocket-server_test.go]: why tests for only two functions?

**Review by shahzadhaider1 — CHANGES_REQUESTED** [review]

File: cmd/chat_app_server/main.go (hunk 1 above)
Comment (Hammad887) [reply cmd/chat_app_server/main.go]: sorted

File: db/mysql/ops.go (hunk 2 above)
Comment (Hammad887) [reply db/mysql/ops.go]: deleted

File: swagger.yaml (hunk 6 above)
Comment (Hammad887) [reply swagger.yaml]: changed

File: websocket/websocket-server.go (hunk 7 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: sorted

File: websocket/websocket-server.go (hunk 10 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Added

File: websocket/websocket-server.go (hunk 11 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Added

File: websocket/websocket-server.go (hunk 14 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: added

File: swagger.yaml (hunk 3 above)
Comment (Hammad887) [reply swagger.yaml]: changed

File: swagger.yaml (hunk 4 above)
Comment (Hammad887) [reply swagger.yaml]: done

File: websocket/websocket-server.go (hunk 12 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server_test.go (hunk 16 above)
Comment (Hammad887) [reply websocket/websocket-server_test.go]: deleted

File: websocket/websocket-server_test.go (hunk 17 above)
Comment (Hammad887) [reply websocket/websocket-server_test.go]: Tests added for all the functions

File: swagger.yaml (hunk 5 above)
Comment (Hammad887) [reply swagger.yaml]: Can't think of anything on top of my head right now. Deleted 400 for now.

File: websocket/websocket-server.go (hunk 15 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: This function was unnecessary. Have deleted it.

File: websocket/websocket-server.go (hunk 13 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server.go (hunk 8 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: I have integrated some changes in the models package and using it here now without making a new struct

File: websocket/websocket-server.go (hunk 9 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: My bad. Was blindly following web implementations.. Made a minor change in main.go file. Now only one db client in the application.

File: cmd/chat_app_server/main.go (hunk 1 above)
Comment (shahzadhaider1) [reply cmd/chat_app_server/main.go]: here is the correct sort order of imports:
1. Standard Library Packages: Import standard library packages first.
2. Third-Party Packages: Import external (third-party) packages second. These are packages not part of the standard library.
3. Local Packages: Import your own local packages third. These are packages that are part of your project.

**Review by shahzadhaider1 — CHANGES_REQUESTED** [review]

File: cmd/chat_app_server/main.go (hunk 1 above)
Comment (Hammad887) [reply cmd/chat_app_server/main.go]: I read somewhere that goimports automatically does that for you. I just realized that goimports only separates standard library imports from third-party imports, but does not differ between third-party imports and own local imports. Sorted now

File: models/user.go [hunk 18]
```diff
@@ -1,9 +1,12 @@
...
 type User struct {
-	ID       string `json:"id"`
-	Name     string `json:"name"`
-	Email    string `json:"email"`
-	Password string `json:"-"`
+	ID         string          `json:"id"`
+	Name       string          `json:"name"`
+	Email      string          `json:"email"`
+	Password   string          `json:"-"`
+	Connection *websocket.Conn `json:"connection,omitempty"`
```
Comment (shahzadhaider1) [inline models/user.go]: why not create a new struct in your model layer that represents a WebSocket connection, which includes the "Connection *websocket.Conn" field. This struct can be something like `WebSocketConnection`.

Comment (shahzadhaider1) [reply models/user.go]: I want you to take a moment and think about this and come up with an optimal approach (according to you)

**Review by shahzadhaider1 — CHANGES_REQUESTED** [review]

**Comment by shahzaibaziz** [comment]
please attach demo screenshots

**Comment by Hammad887** [comment]
I have uploaded a small video to demo the functionality. Here's the link: https://drive.google.com/file/d/1l31IjJrvoWk9nmKk_Wq9_xtkHosbXgx2/view?usp=sharing

**Comment by shahzadhaider1** [comment]
Hammad, that's impressive. 
1. But I didn’t see any authentication being performed at the beginning. You didn’t provide any credentials, etc. did you do it before making the video? 
2. Could you create a third user and connect that user to a different chatroom and then send the message in the chatroom where first and second user are present? Now, this third user shouldn’t receive the message since this user is not a part of the chatroom where the message was sent.

File: models/chatroom.go [hunk 19]
```diff
@@ -2,7 +2,11 @@ package models
 
 // ChatRoom holds information for the users inside a particular chat room
 type ChatRoom struct {
-	ID    string   `json:"id"`
-	Name  string   `json:"name"`
-	Users []string `json:"users"`
+	ID                 string   `json:"id"`                           // to hold the ID of User
+	Name               string   `json:"name"`                         // to hold the Name of User
+	Users              []string `json:"users"`                        // to hold array of ID of Users
+	ClientWsConnection []*User  `json:"ClientWsConnection,omitempty"` // to hold array of User's complete struct information with websocket connection address
```
Comment (shahzaibaziz) [inline models/chatroom.go]:
```suggestion
	ClientWsConnection []*User  `json:"client_ws_connection,omitempty"` // to hold array of User's complete struct information with websocket connection address
```

File: cmd/chat_app_server/main.go [hunk 20]
```diff
@@ -29,6 +30,8 @@ func main() {
 
 	handler.NewCustomHandler(api, rt)
 
+	go websocket.RunWebsocketServer(rt)
+
```
Comment (shahzaibaziz) [inline cmd/chat_app_server/main.go]: Instead of creating a new server, have you considered adding this as middleware in this file?https://github.com/Hammad887/chat-app/blob/master/gen/restapi/configure_chatroom.go#L98

**Comment by Hammad887** [comment]
@shahzadhaider1 Yes, I did the authentication before making the video. Also, here's another video for the 3rd user you wanted me to create and test with the previously made chatroom. Link: https://drive.google.com/file/d/11YbK8n_fTDpPK8bKAxlg9wGoZyLLb9RB/view?usp=sharing

File: cmd/chat_app_server/main.go (hunk 20 above)
Comment (Hammad887) [reply cmd/chat_app_server/main.go]: Looking into this

File: models/chatroom.go (hunk 19 above)
Comment (Hammad887) [reply models/chatroom.go]: Done

**Comment by shahzadhaider1** [comment]
Alright, good work.

File: models/user.go (hunk 18 above)
Comment (Hammad887) [reply models/user.go]: The best approach I could think of after some research as well was to make separate structs for both user and chatroom connection field. Pushed the latest for review.

File: cmd/chat_app_server/main.go (hunk 20 above)
Comment (Hammad887) [reply cmd/chat_app_server/main.go]: Good to go

Comment (shahzaibaziz) [reply cmd/chat_app_server/main.go]: We need to create a separate main function to run the WebSocket server within the cmd folder, specifically in chat-app-websocket/main.go. Additionally, we should establish a different entry point in the Docker service in your docker-compose file. This will involve defining two separate services, one for the chat server and the other for the WebSocket server.

File: models/websocket-user.go [hunk 21]
```diff
@@ -0,0 +1,9 @@
+package models
+
+import "github.com/gorilla/websocket"
+
+// WebsocketUser holds information for a WebsocketUser user
+type WebsocketUser struct {
+	ID         string          `json:"id"`
+	Connection *websocket.Conn `json:"connection,omitempty"`
```
Comment (shahzaibaziz) [inline models/websocket-user.go]: can you please explain why we are storing the connection string to the database?

File: swagger.yaml [hunk 22]
```diff
@@ -47,6 +47,32 @@ paths:
             type: string
           description: Server error
 
+  /createChatRoom:
```
Comment (shahzaibaziz) [inline swagger.yaml]: It should be 'create-chat-room,' which follows the basic convention used in APIs

File: websocket/websocket-enums.go
Comment (shahzaibaziz) [inline websocket/websocket-enums.go:1]: rename this file to constant

File: websocket/websocket-enums.go [hunk 23]
```diff
@@ -0,0 +1,11 @@
...
+
+//Defines Websocket enums
+
+const RequestTypeChatRoom = "connect_to_chat_room"
+const RequestTypeSendMessage = "send_message"
+const RequestParamRoomId = "room_id"
+const RequestParamSenderId = "sender_id"
+const RequestParamMessageFrom = "message_from"
+const RequestParamMessage = "message"
+const RequestParamRequestType = "requestType"
```
Comment (shahzaibaziz) [inline websocket/websocket-enums.go]:
```suggestion
const (
 RequestTypeChatRoom = "connect_to_chat_room"
 RequestTypeSendMessage = "send_message"
RequestParamRoomId = "room_id"
RequestParamSenderId = "sender_id"
RequestParamMessageFrom = "message_from"
RequestParamMessage = "message"
RequestParamRequestType = "requestType"
)
```
Arrange them in alphabetical order

File: websocket/websocket-server.go [hunk 24]
```diff
@@ -0,0 +1,335 @@
...
+	"github.com/gorilla/handlers"
+	"github.com/gorilla/mux"
+	"github.com/gorilla/websocket"
+
+	runtime "github.com/Hammad887/chat-app"
+	domain "github.com/Hammad887/chat-app/models"
+)
+
+// ctx is a variable of type context.Context, which is used to manage request-scoped values, deadlines, and cancellations.
+var ctx context.Context
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: why we are using this context here, it should be passed from the main file , like we are using the swagger server

File: websocket/websocket-server.go [hunk 25]
```diff
@@ -0,0 +1,335 @@
...
+
+	// EnableCompression allows for message compression when set to true.
+	EnableCompression: true,
+
+	// CheckOrigin is a function that checks the origin of the WebSocket request to prevent cross-origin attacks.
+	// In this case, it's set to always return true, meaning any origin is accepted.
+	CheckOrigin: func(r *http.Request) bool {
+		return true
+	},
+}
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: Please remove the whole  logic from your server. In an ideal situation, microservices are not publicly exposed directly to the internet. Instead, we typically use a server-client proxy (e.g., Nginx) that serves as the public-facing entry point to your server

File: websocket/websocket-server.go [hunk 26]
```diff
@@ -0,0 +1,335 @@
...
+	headers := handlers.AllowedHeaders([]string{"*"})
+	origins := handlers.AllowedOrigins([]string{"*"}) // Allow requests from any origin
+
+	// Add CORS middleware
+	router.Use(handlers.CORS(headers, origins))
+
+	router.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
+		ClientSocket(w, r, rt)
+	})
+	fmt.Println("Server is running on port 8085")
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: it should be and thus logic move to main file

File: websocket/websocket-server.go [hunk 27]
```diff
@@ -0,0 +1,335 @@
...
+
+	// Start your server
+	go func() {
+		err := http.ListenAndServe(":8085", router)
+		if err != nil {
+			log.Println(err)
+		}
+	}()
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: move to main file

File: websocket/websocket-server.go [hunk 28]
```diff
@@ -0,0 +1,335 @@
...
+}
+
+// ClientSocket handles incoming WebSocket connections from clients.
+func ClientSocket(w http.ResponseWriter, r *http.Request, rt *runtime.Runtime) {
+
+	Conn, err := upgrader.Upgrade(w, r, nil)
+	if err != nil {
+		log.Print("upgrade:", err)
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: handle error correctly, it should pass to the  handler and return error message

File: websocket/websocket-server.go [hunk 29]
```diff
@@ -0,0 +1,335 @@
...
+		return
+	}
+	defer func(Conn *websocket.Conn) {
+		err := Conn.Close()
+		if err != nil {
+			log.Println(err)
+		}
+	}(Conn)
+
+	rt.Service()
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: remove this

File: websocket/websocket-server.go [hunk 30]
```diff
@@ -0,0 +1,335 @@
...
+	service := rt.Service()
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: this logic should be in runtime

Comment (shahzaibaziz) [reply websocket/websocket-server.go]: you can use a flag list in NewRuntime function to create a different runtime for websocket server and chat server

File: websocket/websocket-server.go [hunk 31]
```diff
@@ -0,0 +1,335 @@
...
+		if err != nil {
+			log.Println("ERROR read: ", err.Error())
+			break
+		}
+
+		requestJson := make(map[string]interface{})
+		err = json.Unmarshal(requestByte, &requestJson)
+		if err != nil {
+			log.Println(err)
+			return
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: error handling issue

File: websocket/websocket-server.go [hunk 32]
```diff
@@ -0,0 +1,335 @@
...
+		}
+		switch requestJson[RequestParamRequestType] {
+		case RequestTypeChatRoom:
+
+			if _, ok := requestJson[RequestParamRoomId]; ok {
+				if !ok {
+					Response := make(map[string]interface{})
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: use this on top of switch

File: websocket/websocket-server.go [hunk 33]
```diff
@@ -0,0 +1,335 @@
...
+					Response[RequestParamRequestType] = RequestTypeChatRoom
+					Response[RequestParamMessage] = "required " + RequestParamRoomId
+					responseBytes, _ := json.Marshal(Response)
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: unhandled error

File: websocket/websocket-server.go [hunk 34]
```diff
@@ -0,0 +1,335 @@
...
+					break
+				}
+			}
+
+			if _, ok := requestJson[RequestParamSenderId]; ok {
+				if !ok {
+					Response := make(map[string]interface{})
+					Response[RequestParamRequestType] = RequestTypeChatRoom
+					Response[RequestParamMessage] = "required " + RequestParamSenderId
+					responseBytes, _ := json.Marshal(Response)
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: unhandled error

File: websocket/websocket-server.go [hunk 35]
```diff
@@ -0,0 +1,335 @@
...
+				}
+			}
+
+			roomId, ok := requestJson[RequestParamRoomId].(string)
+
+			if !ok {
+				Response := make(map[string]interface{})
+				Response[RequestParamRequestType] = RequestTypeChatRoom
+				Response[RequestParamMessage] = "required string type " + RequestParamRoomId
+				responseBytes, _ := json.Marshal(Response)
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: same as above

File: websocket/websocket-server.go [hunk 36]
```diff
@@ -0,0 +1,335 @@
...
+					responseBytes, _ := json.Marshal(Response)
+					WriteOnSocket(responseBytes, messageType, Conn)
+					break
+				}
+			}
+
+			roomId, ok := requestJson[RequestParamRoomId].(string)
+
+			if !ok {
+				Response := make(map[string]interface{})
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: same as above

File: websocket/websocket-server.go [hunk 37]
```diff
@@ -0,0 +1,335 @@
...
+				Response[RequestParamRequestType] = RequestTypeChatRoom
+				Response[RequestParamMessage] = "required string type " + RequestParamRoomId
+				responseBytes, _ := json.Marshal(Response)
+				WriteOnSocket(responseBytes, messageType, Conn)
+				break
+			}
+
+			senderId, ok := requestJson[RequestParamSenderId].(string)
+			if !ok {
+				Response := make(map[string]interface{})
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: avoid creating a same variable in each case declare this on top of switch

File: websocket/websocket-server.go [hunk 38]
```diff
@@ -0,0 +1,335 @@
...
+				Response[RequestParamRequestType] = RequestTypeChatRoom
+				Response[RequestParamMessage] = "required string type " + RequestParamSenderId
+				responseBytes, _ := json.Marshal(Response)
+				WriteOnSocket(responseBytes, messageType, Conn)
+				break
+			}
+
+			row, _ := service.GetChatroom(ctx, roomId)
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: handle error,

File: websocket/websocket-server.go [hunk 39]
```diff
@@ -0,0 +1,335 @@
...
+		err := Conn.Close()
+		if err != nil {
+			log.Println(err)
+		}
+	}(Conn)
+
+	rt.Service()
+	service := rt.Service()
+
+	for {
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: why using infinite loop here?

File: websocket/websocket-server.go [hunk 40]
```diff
@@ -0,0 +1,335 @@
...
+			break
+		}
+
+		requestJson := make(map[string]interface{})
+		err = json.Unmarshal(requestByte, &requestJson)
+		if err != nil {
+			log.Println(err)
+			return
+		}
+		switch requestJson[RequestParamRequestType] {
```
Comment (shahzaibaziz) [inline websocket/websocket-server.go]: One major thing is missing here: in the case of an error, the error message must be displayed in Postman, this message is related to all the cases in a switch

Comment (shahzaibaziz) [reply websocket/websocket-server.go]: Reduce the redundancy in the code

File: websocket/websocket-server_test.go [hunk 41]
```diff
@@ -0,0 +1,164 @@
...
+			},
+		},
+		{
+			name: "InvalidCheckConnection",
+			args: args{
+				responseBytes: []byte(`{"requestType": "connect_socket"}`),
+				messageType:   websocket.TextMessage,
+				Conn:          conn, // Use the WebSocket connection to the server
+			},
+		},
```
Comment (shahzaibaziz) [inline websocket/websocket-server_test.go]: You don't need to change this, but I have a suggestion for your work. This test doesn't cover the entire server, and there's a significant lack of coverage for each case in your server

**Comment by shahzaibaziz** [comment]
Good work! Kudos to @Hammad887  for putting a lot of effort into it

File: swagger.yaml (hunk 22 above)
Comment (Hammad887) [reply swagger.yaml]: changed

File: websocket/websocket-enums.go
Comment (Hammad887) [reply websocket/websocket-enums.go:1]: Done

File: websocket/websocket-enums.go (hunk 23 above)
Comment (Hammad887) [reply websocket/websocket-enums.go]: Done

File: cmd/chat_app_server/main.go (hunk 20 above)
Comment (Hammad887) [reply cmd/chat_app_server/main.go]: Created a separate main function to run the WebSocket server. Will discuss about Dockerfile and docker-compose file during a call.

File: models/websocket-user.go (hunk 21 above)
Comment (Hammad887) [reply models/websocket-user.go]: I read online that it's a good practice for microservice architecture. It is basically used for secure communication and service-to-service authorization/authentication. For example, it will ensure that a user can only connect to a WebSocket if they have a valid token.

File: websocket/websocket-server.go (hunk 24 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Using context.Background() in the main file.

File: websocket/websocket-server.go (hunk 25 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Removed

File: websocket/websocket-server.go (hunk 26 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server.go (hunk 27 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server.go (hunk 28 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server.go (hunk 29 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Removed

File: websocket/websocket-server.go (hunk 30 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server.go (hunk 31 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Resolved

File: websocket/websocket-server.go (hunk 32 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Moved

File: websocket/websocket-server.go (hunk 33 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Resolved

File: websocket/websocket-server.go (hunk 34 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Resolved

File: websocket/websocket-server.go (hunk 35 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Resolved

File: websocket/websocket-server.go (hunk 36 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Resolved

File: websocket/websocket-server.go (hunk 37 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server.go (hunk 38 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: Done

File: websocket/websocket-server.go (hunk 39 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: I am using break statements. The loop will terminate when the connection breaks.

File: websocket/websocket-server.go (hunk 40 above)
Comment (Hammad887) [reply websocket/websocket-server.go]: All error messages are displaying in Postman.

Comment (Hammad887) [reply websocket/websocket-server.go]: Added a function at the end to reduce the redundancy

File: websocket/websocket-server_test.go (hunk 41 above)
Comment (Hammad887) [reply websocket/websocket-server_test.go]: Will keep it under consideration in the future. Thank You!

**Comment by Hammad887** [comment]
@shahzaibaziz I have changed all the filenames to snake case. Thank you so much for imparting this knowledge. Also, added a websocket handler which addresses most of the changes you asked me to resolve in the websocket-server.go file in the previous commit.

I will need to discuss the dockerfile and docker-compose on a call once everything else gets resolved.

File: docker-compose.yaml [hunk 42]
```diff
@@ -43,4 +65,4 @@ services:
     volumes:
       - ./swagger.yaml:/swagger.yaml
     environment:
-      SWAGGER_JSON: /swagger.yaml
\ No newline at end of file
+      SWAGGER_JSON: /swagger.yaml
```
Comment (shahzadhaider1) [inline docker-compose.yaml:60]: leave blank line at the end

File: docker-compose.yaml [hunk 43]
```diff
@@ -35,6 +37,26 @@ services:
...
+    container_name: chatroom_websocket
+    depends_on:
+      - db
+    environment:
+      HOST: 0.0.0.0
+      PORT: 8085
+      # MYSQL_DB_HOSTS: mysql:3306
+      # MYSQL_DB_NAME: userdb
+      # MYSQL_DB_USERNAME: root
+      # MYSQL_DB_PASSWORD: password
```
Comment (shahzadhaider1) [inline docker-compose.yaml]: remove these comments if not required

File: handlers/websocket.go [hunk 44]
```diff
@@ -0,0 +1,301 @@
...
+	"github.com/Hammad887/chat-app/service"
+)
+
+const (
+	RequestParamMessage     = "message"
+	RequestParamMessageFrom = "message_from"
+	RequestParamRequestType = "requestType"
+	RequestParamRoomId      = "room_id"
+	RequestParamSenderId    = "sender_id"
+	RequestTypeChatRoom     = "connect_to_chat_room"
```
Comment (shahzadhaider1) [inline handlers/websocket.go]: we can make it more descriptive

File: models/chatroom.go [hunk 45]
```diff
@@ -2,7 +2,7 @@ package models
 
 // ChatRoom holds information for the users inside a particular chat room
 type ChatRoom struct {
-	ID    string   `json:"id"`
-	Name  string   `json:"name"`
-	Users []string `json:"users"`
+	ID    string   `json:"id"`    // to hold the ID of User
+	Name  string   `json:"name"`  // to hold the Name of User
```
Comment (shahzadhaider1) [inline models/chatroom.go]: update the comments

File: models/websocket_chatroom.go [hunk 46]
```diff
@@ -0,0 +1,10 @@
+package models
+
+// WebsocketChatRoom holds information for the users inside a particular chat room
+type WebsocketChatRoom struct {
+	ID                 string           `json:"id"`                             // to hold the ID of User
```
Comment (shahzadhaider1) [inline models/websocket_chatroom.go]: is this the ID of user?

**Review by shahzadhaider1 — CHANGES_REQUESTED** [review]

File: docker-compose.yaml (hunk 42 above)
Comment (Hammad887) [reply docker-compose.yaml:60]: Pushed the code again after adding the file, but it still isn't showing up here.

File: handlers/websocket.go (hunk 44 above)
Comment (Hammad887) [reply handlers/websocket.go]: Using Prefix Constants and Clear Naming now.

File: models/chatroom.go (hunk 45 above)
Comment (Hammad887) [reply models/chatroom.go]: updated

File: models/websocket_chatroom.go (hunk 46 above)
Comment (Hammad887) [reply models/websocket_chatroom.go]: My bad. Changed it to the ID of ChatRoom

File: cmd/chat_app_socket_server/main.go [hunk 47]
```diff
@@ -0,0 +1,47 @@
...
+	// Set up CORS handling
+	headers := request.AllowedHeaders([]string{"*"})
+	origins := request.AllowedOrigins([]string{"*"}) // Allow requests from any origin
+
+	// Add CORS middleware
+	router.Use(request.CORS(headers, origins))
+
+	rt, err := runtime.NewRuntime()
+	if err != nil {
+		log.Println(err)
```
Comment (shahzaibaziz) [inline cmd/chat_app_socket_server/main.go]:
```suggestion
		panic(err)
```

File: cmd/chat_app_socket_server/main.go [hunk 48]
```diff
@@ -0,0 +1,47 @@
...
+	}
+
+	service := rt.Service()
+
+	router.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
+		err = handlers.WebSocketHandler(w, r, service, ctx)
```
Comment (shahzaibaziz) [inline cmd/chat_app_socket_server/main.go]: paramter should be runtime object not service object

File: cmd/chat_app_socket_server/main.go [hunk 49]
```diff
@@ -0,0 +1,47 @@
...
+		if err != nil {
+			log.Println(err)
+		}
+	})
+
+	fmt.Println("Server is running on port 8085")
+	err = http.ListenAndServe(":8085", router)
+	if err != nil {
+		log.Println(err)
```
Comment (shahzaibaziz) [inline cmd/chat_app_socket_server/main.go]: panic

File: cmd/chat_app_socket_server/main.go [hunk 50]
```diff
@@ -0,0 +1,47 @@
...
+
+	router.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
+		err = handlers.WebSocketHandler(w, r, service, ctx)
+		if err != nil {
+			log.Println(err)
+		}
+	})
+
+	fmt.Println("Server is running on port 8085")
+	err = http.ListenAndServe(":8085", router)
```
Comment (shahzaibaziz) [inline cmd/chat_app_socket_server/main.go]: its better to use env variable for port number

File: docker-compose.yaml [hunk 51]
```diff
@@ -35,6 +37,26 @@ services:
...
+      dockerfile: dockerfile.chat_app_socket_server
+    container_name: chatroom_websocket
+    depends_on:
+      - db
+    environment:
+      HOST: 0.0.0.0
+      PORT: 8085
+      # MYSQL_DB_HOSTS: mysql:3306
+      # MYSQL_DB_NAME: userdb
+      # MYSQL_DB_USERNAME: root
```
Comment (shahzaibaziz) [inline docker-compose.yaml]: This Dockerfile change is also acceptable, but there is another way to build binary files during the 'make build' process and run binary files with the help of bash scripts. The consumption has the same implementation

File: docker-compose.yaml (hunk 42 above)
Comment (shahzaibaziz) [reply docker-compose.yaml:60]: If you plan to provide an API specification page, you'll need to expose the port so that anyone who wants to view the API spec can do so by accessing the host and port to see the API documentation

File: handlers/sendMessage.go
Comment (shahzaibaziz) [inline handlers/sendMessage.go:1]: rename to send_message.go to consist with project

**Review by shahzaibaziz — COMMENTED** [review]
minor comments other than that LGTM

File: .DS_Store
Comment (shahzaibaziz) [inline .DS_Store:1]: remove this

File: cmd/chat_app_socket_server/main.go (hunk 47 above)
Comment (Hammad887) [reply cmd/chat_app_socket_server/main.go]: Changed

File: cmd/chat_app_socket_server/main.go (hunk 49 above)
Comment (Hammad887) [reply cmd/chat_app_socket_server/main.go]: Changed

File: handlers/sendMessage.go
Comment (Hammad887) [reply handlers/sendMessage.go:1]: Done

File: .DS_Store
Comment (Hammad887) [reply .DS_Store:1]: Removed

File: cmd/chat_app_socket_server/main.go (hunk 50 above)
Comment (Hammad887) [reply cmd/chat_app_socket_server/main.go]: Done

File: cmd/chat_app_socket_server/main.go (hunk 48 above)
Comment (Hammad887) [reply cmd/chat_app_socket_server/main.go]: Changed

File: docker-compose.yaml (hunk 51 above)
Comment (Hammad887) [reply docker-compose.yaml]: Will look into this.

File: docker-compose.yaml (hunk 43 above)
Comment (Hammad887) [reply docker-compose.yaml]: Removed.

File: cmd/chat_app_socket_server/main.go [hunk 52]
```diff
@@ -0,0 +1,56 @@
...
+	"net/http"
+	"os"
+
+	"github.com/gorilla/mux"
+	"github.com/joho/godotenv"
+
+	runtime "github.com/Hammad887/chat-app"
+	"github.com/Hammad887/chat-app/handlers"
+	request "github.com/gorilla/handlers"
+)
```
Comment (shahzadhaider1) [inline cmd/chat_app_socket_server/main.go]: please sort imports

Comment (Hammad887) [reply cmd/chat_app_socket_server/main.go]: Sorted

**Review by shahzadhaider1 — APPROVED** [review]
LGTM. Please resolve Shahzaib's comment and you’ll be good to merge.
GW!
